### ISSUE TITLE
firmware M3

### ISSUE THREAD

**Issue by kostyainmadness** [Draiget/whatsminer-fakefan#1]
With what firmware working this script?
I have Whatsminer M3 and autofreq firmware, just tested script with connected fan, but it not work :(

**Comment by Draiget** [comment]
Should work with all firmware versions, you just need to place **fake_fan.sh** to the **/etc** folder of asic device, apply execute permissions (`chmod +x /etc/fake_fan.sh`) and execute script itself. Then cgminer should get fake values of fans PWM. 
If you still had issues, then can you please say what are you doing step by step?

**Comment by kostyainmadness** [comment]
Hi! Thank for support.
I made all steps in manual. fake_fan.sh with execute permission. When i run script, my ssh session disconnect in same second (dont know why),  in log i see "Sat Apr  6 12:37:59 2019 user.notice fake_fan: Fake path mounted", but in web interface all my fans still around 3000 RPMs.

**Comment by Draiget** [comment]
@kostyainmadness we can try investigate this problem together, if you had Telegram you can add me by nickname @Draiget.

**Comment by Draiget** [comment]
We figured out the problem with @kostyainmadness, **fake_fan.sh** script was not fully copied. Guys make sure that u're copy it exactly like it present in git repository.

**Comment by kostyainmadness** [comment]
Thank you for support!
Script is working, it was my mistake!

**Comment by meysamsiyar** [comment]
What is copying?
