### ISSUE TITLE
permission denied (newer firmware)

### ISSUE THREAD

**Issue by morsine** [Draiget/whatsminer-fakefan#7]
Hello and good evenings !
With the newer firmware, there is no root access :(
so therefor, the steps explained in your guide cannot be proceeded.
Can you please provide us with an older firmware with root access, or a new one with root access.
Thank you !!

**Comment by morsine** [comment]
It's been a while, so here's what you have to do in order to gain root on the newer firmware:
There are TTL pins on the control board, connect them to a TTL to USB or something like that.
Open the TTL in your terminal, like this `screen /dev/ttyusb0` now you have root access!
run passwd in order to set root password. after that, login via SSH as root.

**Comment by K5rovski** [comment]
Hello, Good Day,
 I know this thread is closed, 
but can @Morsine please provide more info, what ttl usb cable is needed to open ssh connections, 
how many pins,
 what chip should be in the adapter and
  what are other useful specs, for Whatsminer m20s miner h3 control board.

thanks.

**Comment by morsine** [comment]
> Hello, Good Day,
> I know this thread is closed,
> but can @Morsine please provide more info, what ttl usb cable is needed to open ssh connections,
> how many pins,
> what chip should be in the adapter and
> what are other useful specs, for Whatsminer m20s miner h3 control board.
> 
> thanks.

Hello and good evenings!
This whatsminer fakefan requires root and read-write file system which is only possible under root, but the updated devices have root closed by default and the user uses "admin" instead of "root"
So in order to gain root access/unlock root access to your whatsminer control board you'll need to access the terminal via the TTL connection.
![controlboard](https://user-images.githubusercontent.com/19589644/123484380-7af1e180-d61d-11eb-86c9-5535a6059090.jpg)
Here there are 3 pins: RX, TX and GND
usually a TTL to USB converter is used, but you can use anything as long as it can open TTL connections (Like arduino and raspberry pi, with some modifications)
The same pins can be seen on a TTL to USB convertor
![usb_to_rs232_ttl_converter_module_adapter_board](https://user-images.githubusercontent.com/19589644/123484829-3fa3e280-d61e-11eb-96ba-fd510fc92353.png)
TX from control board connects to RX from convertor
RX from control board connects to TX from convertor
GND from control board connect to GND from convertor
than plug in the convertor to your computer.

if you're using windows:
1- [download putty](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)
2- open device manager, under "Ports (COM & LPT) you should see a com port, for example COM28
3- open putty, select serial, enter COM28 (or anything you saw in device manager) than hit enter
4- you have a root shell to the control board. type "passwd" and hit enter, this way you'll set the root password
5- do the guide as described but login as root instead of admin.

Note: you might need to install drivers related to the convertor your using.

if you're using Linux:
1- install screen (for example on debian "apt-get install screen")
2- execute this "dir /dev/" and check for anything ttyUSB, like ttyUSB1 or ttyUSB0
3- run screen /dev/ttyUSB0 (or ttyUSB1 or anything you saw when executing the previous command)
4- you have a root shell to the control board. type "passwd" and hit enter, this way you'll set the root password
5- do the guide as described but login as root instead of admin.

**Please note that your miner can get damaged if you modify wrong files. (for example the clock speed files related to your hash boards) so do this at your own risk.**

If I can help you further, I'd be happy to do so. and if you got the fake fan to work, I'll be thankful if you let me know how you did it. mine detects that something is wrong with the fans and won't start.

**Comment by bestman811** [comment]
hi i cant change password it say its too short
admin@WhatsMiner:~$ passwd
Changing password for admin
Old password:
New password:
Bad password: too short
passwd: password for admin is unchanged

**Comment by morsine** [comment]
Try a longer password, possibly one with both letters and numbers.
